In [67]:
import numpy as np

#Numpy’da Vektor ve Matrisin farkini tek cumle ile ifade ediniz.
#Vektörler, tek boyutlu matrislerdir.

In [3]:
#10 elemanli bir listeden NumPy Array’i olusturunuz.
a= [3,4,5,6,7,8,9,10,11,12]

np.array(a)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [4]:
#Icerisinde ‘0’ lar olan, ve veri tipi integer olan 10X10’luk bir matris olusturunuz.
np.zeros((10,10) ,dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [5]:
#Icerisinde ‘1’ ler olan, veri tipi float olan 10X10’luk bir matris olusturunuz.
np.ones((10,10),dtype=float)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [6]:
#Icerisinde ‘9’ lar olan, veri tipi integer olan 10X10’luk bir matris olusturunuz.
np.full((10,10) , 9 ,dtype=int)

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [7]:
#5 ile 25 arasinda, 3’er 3’er atlayan tek boyutlu bir Array olusturunuz.
np.arange(5,25,3)

array([ 5,  8, 11, 14, 17, 20, 23])

In [176]:
#-1 ile 1 arasinda 30 adet Array olusturunuz.



ValueError: negative dimensions are not allowed

In [16]:
#0 ile 30 arasinda 5x6’lik bir matris olusturun.
np.arange(0,30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [21]:
#Kosegenleri 1 olan 10x10’luk bir matris olusturunuz.
np.eye(10,10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [31]:
#0 ile 10 arasinda 5x10’lik bir matris olusturun. (integer) ve bu matrisin; 
b=np.random.randint(0,10,(5,10),dtype=int)
print(b)
# • eleman sayisini 
print(b.size)

# • boyut bilgisini/sayisini 
print(b.ndim)

# • satir X sutun bilgisini 
print(b.shape)

# • veri tipini numpy metodlariyla yazdiriniz.
print(b.dtype)


[[8 7 0 0 8 9 8 4 8 6]
 [8 1 6 1 8 8 5 6 7 0]
 [6 6 0 7 7 8 5 4 0 5]
 [6 7 6 3 3 4 3 4 2 3]
 [6 5 1 9 9 6 4 3 9 8]]
50
2
(5, 10)
int32


In [33]:
#0 ile 10 arasindaki degerlerden olusan 3 adet 4x7’lik bir matris olusturunuz. (3 boyutlu bir matris olusturulacak)
np.random.randint(0,10,(3,4,7),dtype=int)

array([[[7, 1, 9, 1, 1, 2, 8],
        [3, 1, 4, 6, 7, 3, 7],
        [0, 6, 2, 1, 9, 2, 3],
        [5, 8, 1, 8, 5, 2, 2]],

       [[5, 2, 9, 6, 1, 0, 6],
        [1, 8, 0, 1, 8, 3, 5],
        [9, 8, 2, 2, 8, 8, 0],
        [2, 2, 3, 3, 0, 6, 8]],

       [[1, 3, 4, 5, 9, 2, 0],
        [5, 4, 1, 7, 8, 8, 5],
        [1, 5, 4, 1, 3, 6, 6],
        [0, 7, 8, 3, 6, 2, 9]]])

In [45]:
#Bir vektor olusturunuz ve daha sonrasinda ayni vektoru bir matrise ceviriniz. (boyut sayisini degistirin.)
c=np.arange(1,13)
print(c)
print(c.reshape(3,4))


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [49]:
#4 tane ayri tek boyutlu array’i birlestirerek bir array olusturunuz.#
e=np.arange(1,4)
f=np.arange(2,8)
g=np.arange(8,12)
h=np.arange(1,6)

print(np.concatenate([e,f,g,h]))

[ 1  2  3  2  3  4  5  6  7  8  9 10 11  1  2  3  4  5]


In [62]:
#2 boyutlu bir vektor ve bir matris olusturun(ayri ayri), bu iki arrayi numpy metodlarini kullanarak sutun bazli birlestiriniz.
i=np.arange(7,10).reshape(3,1)
print(i)
j=np.arange(1,7).reshape(3,2)
print(j)
np.concatenate([i,j], axis=1)

[[7]
 [8]
 [9]]
[[1 2]
 [3 4]
 [5 6]]


array([[7, 1, 2],
       [8, 3, 4],
       [9, 5, 6]])

In [ ]:
#Numpy’da “axis=1” ve “axis=0” arasinda ne fark vardir. Teorik olarak yaziniz?
# axis= 0 : satir bazli
# axis= 1 : sütun bazli

In [74]:
#Farkli boyutlardaki arraylari satir ve sutun bazli ayri ayri birlestiriniz.
k=np.arange(1,7).reshape(3,2)
l=np.arange(7,13).reshape(3,2)
print(np.concatenate([k,l], axis=0))
print(np.concatenate([k,l], axis=1))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  2  7  8]
 [ 3  4  9 10]
 [ 5  6 11 12]]


In [78]:
#10 elemanli bi liste olusturunuz ve bu listeyi Numpy metodlariyla bolerek(split) 5 ayri array olusturunuz.
m=np.arange(1,11)
np.split(m, [2,4,6,8])

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]

In [82]:
# Random bir array olusturunuz ve bu arrayi buyukten kucuge dogru siralayiniz.
# Ve bu siralamadan sonra hangi elemanin hangi indexte oldugunu gosteren bir metod uygulayiniz.

n= np.array([3,2,5,77,6,43,5,12])
n_sort= np.sort(n)

print(n)    #n'de siralama degismedi!
print(n_sort)

for i in range(len(n_sort)):
    for j in range(len(n)):
        if n_sort[i] ==  n[j]:
            print(f"{n_sort[i]} elemaninin n listesinde indexi : {j}")
    

[ 3  2  5 77  6 43  5 12]
[ 2  3  5  5  6 12 43 77]
2 elemaninin n listesinde indexi : 1
3 elemaninin n listesinde indexi : 0
5 elemaninin n listesinde indexi : 2
5 elemaninin n listesinde indexi : 6
5 elemaninin n listesinde indexi : 2
5 elemaninin n listesinde indexi : 6
6 elemaninin n listesinde indexi : 4
12 elemaninin n listesinde indexi : 7
43 elemaninin n listesinde indexi : 5
77 elemaninin n listesinde indexi : 3


In [92]:
#20 elemanli random bir vektor olusturunuz. Bu vektorun 3. 5. ve 7. elemanlarina ulasin.
p=np.random.randint(0,30,20)
print(p)
print(p[3], p[5], p[7])

[17 12 16 22 29  4  5  0 11 16  2 28  1 27  3 15  7 26 14 13]
22 4 0


In [94]:
#10 elemanli random bir vektor olusturunuz ve bu arrayin 4. elemanini farkli bir sayiyla degistiriniz.
r=np.random.randint(0,20,10)
print(r)
r[4]=99
print(r)

[18  3  7  4  9  8  2 13  2 10]
[18  3  7  4 99  8  2 13  2 10]


In [ ]:
#“Diagonal Matrix” ve “Trace of Matrix” kavramlari hakkinda kucuk bir arastirma yapip bunlarin ne oldugunu belirten kucuk bir aciklama yaziniz.

#Bir kare matriste asal köşegen üzerindeki elemanların dışında kalan tüm elemanlar sıfır ise bu matris diagonaldir.
#Bir kare matrisin köşegen üzerindeki elemanların toplamıdır.

In [101]:
#5x5’lik Diagonal bir matris olusturunuz ve Diagonaline denk gelen indexlere ulasiniz.(ayri ayri)
s=np.random.randint(0,10,5)
print(s)
s_diag= np.diag(s)
print(s_diag)

for i in range(len(s_diag)):
    print(f's_diag{[i,i]} :' , s_diag[i,i])

[2 4 0 5 2]
[[2 0 0 0 0]
 [0 4 0 0 0]
 [0 0 0 0 0]
 [0 0 0 5 0]
 [0 0 0 0 2]]
s_diag[0, 0] : 2
s_diag[1, 1] : 4
s_diag[2, 2] : 0
s_diag[3, 3] : 5
s_diag[4, 4] : 2


In [106]:
#10 ile 20 arasinda bir vektor olusturunuz. Ve 3. indexten son indexe kadar olan degerleri yazdiriniz.

t=np.arange(10,20)
print(t)
t[3::]

[10 11 12 13 14 15 16 17 18 19]


array([13, 14, 15, 16, 17, 18, 19])

In [133]:
#10X10 luk bir matris olusturunuz ve ; 
u=np.random.randint(0,20,[10,10])
print(u)

[[18  6 18 19  4  8 12  4  7  7]
 [13 19 13  5  8 13  1 15 17 11]
 [11 11  6 15  6  2  3 11 17 19]
 [ 6 15  6 12  6 18  1  6  7 12]
 [16  7 14 19  9 18  5  5  2 18]
 [18  2 14 12  1  2 12  1 12  5]
 [10  7 17 18  9 19 19 11 13  5]
 [ 6 11 15 12 17  9 11  1  2  2]
 [10  8 17 14 16  5  1  0  2 12]
 [ 8  2 15 18 14 13  3  0 11  4]]


In [134]:
# • 3.satir ve 5.sutuna ulasiniz. 
print(u[2,4])
print(50*'-')
# • 5.sutunun tum satirlarina ulasiniz.
print(u[:,4])
print(50*'-')
# • Tum sutunlarin 2.satirlarina ulasiniz. 
print(u[1,:])
print(50*'-')
# • Tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz. 
print(u[2:6, :])
print(50*'-')

6
--------------------------------------------------
[ 4  8  6  6  9  1  9 17 16 14]
--------------------------------------------------
[13 19 13  5  8 13  1 15 17 11]
--------------------------------------------------
[[11 11  6 15  6  2  3 11 17 19]
 [ 6 15  6 12  6 18  1  6  7 12]
 [16  7 14 19  9 18  5  5  2 18]
 [18  2 14 12  1  2 12  1 12  5]]
--------------------------------------------------


In [135]:
# • Satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerlere ulasiniz. 
print(u[1:4 , 2:6])
print(50*'-')
# • Satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerlere ulasiniz. 
print(u[4::,::3])
print(50*'-')
# • Sutun indexi sadece 3, 6, 9 olan kolonlarin(sutunlarin), tum satirlarina ulasiniz. 
print(u[:,[2,5,8]])
print(50*'-')
# • 5.indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistiriniz.
u[5,5]= 1986
print(u[5,:])


[[13  5  8 13]
 [ 6 15  6  2]
 [ 6 12  6 18]]
--------------------------------------------------
[[16 19  5 18]
 [18 12 12  5]
 [10 18 19  5]
 [ 6 12 11  2]
 [10 14  1 12]
 [ 8 18  3  4]]
--------------------------------------------------
[[18  8  7]
 [13 13 17]
 [ 6  2 17]
 [ 6 18  7]
 [14 18  2]
 [14  2 12]
 [17 19 13]
 [15  9  2]
 [17  5  2]
 [15 13 11]]
--------------------------------------------------
[  18    2   14   12    1 1986   12    1   12    5]


In [137]:
# 0’dan 50’ye kadar 5’er 5’er atlayarak giden bir array olusturunuz(tek boyutlu) ve numpy metodlariyla asagidaki islemleri uygulayin;

v=np.arange(0,50,5)
v

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [147]:
# • 20 den buyuk olan kac deger var?
print(f"20'den büyük deger sayisi {v[v>20].size}")
# • 30’dan kucuk kac deger var?
print(f"30'den büyük deger sayisi {v[v<30].size}")
# • icerisinde 33 gecen kac deger var?
print(f"33'e esit deger sayisi {v[v==33].size}")
# • olusturulan arrayin tum elemanlarini 5 ile carpin.
print(v*5)
# • olusturulan arrayin tum elemanlarinin 2 ile bolumunden kalanlari yazdiriniz.
print(v%2)

20'den büyük deger sayisi 5
30'den büyük deger sayisi 6
33'e esit deger sayisi 0
[  0  25  50  75 100 125 150 175 200 225]
[0 1 0 1 0 1 0 1 0 1]


In [162]:
#0 ile 1 arasinda 50 elamanli bir array olusturunuz ve;
y=np.linspace(0,1,50)
print(y)
# • orlamasini aliniz. 
print('Mean: ' , np.mean(y))
# • standart sapmasini aliniz. 
print('Std: ' , np.std(y))
# • varyansini aliniz. 
print('Variance: ' , np.var(y))
# • median’ini aliniz. 
print('Median: ' , np.median(y))
# • en kucuk degeri bulunuz. 
print('Min: ' , np.min(y))
# • en buyuk degeri bulunuz. 
print('Max: ' , np.max(y))


[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]
Mean:  0.5
Std:  0.2945075446869757
Variance:  0.086734693877551
Median:  0.5
Min:  0.0
Max:  1.0


In [ ]:
# Master odev ; Bir dongu icerisinde random olacak sekilde iki tane 20x20’luk matris uretin ve bu matrislerin farklarini alin. 
# Ve fark matrisinin diagonali, -0.1 ile 0.1 arasinda olana kadar bu islemi tekrarlayin. 
# Istenilen matris bulundugunda program dursun ve toplam kac dongunun kuruldugunu, 
# ne kadar sure icinde buldugunu ve istenilen matrisi print ile birlikte ekrana yazdiriniz... 
# Tavsiye: 20 x 20 luk matrisin bulunmasi saatler surebilir. 
# Bu yuzden algoritmanizin dogrulugunu test etmek icin once 4x4, 5x5 gibi kucuk matrislerde deneyebilirsiniz.
# Ve matris sayisisini arttirarak en son 20x20 u deneyebilirsiniz.

In [194]:
x=np.random.rand(5,5)
y=np.random.rand(5,5)
print(x)
print(y)
print(x-y)

[[0.52300101 0.15093834 0.83714388 0.21457231 0.5095156 ]
 [0.61868513 0.32562673 0.48078934 0.23672412 0.88170866]
 [0.29967877 0.54585989 0.55953169 0.278044   0.05476821]
 [0.60920819 0.22079346 0.86654889 0.19809113 0.77122491]
 [0.09646226 0.14797462 0.1917742  0.1899789  0.51346388]]
[[0.63678097 0.8650806  0.73886724 0.13843919 0.51195022]
 [0.22499985 0.79499119 0.87967045 0.83888745 0.66421572]
 [0.86172754 0.01897503 0.54605359 0.72109093 0.74287819]
 [0.99699694 0.1224021  0.36634059 0.39146645 0.36171829]
 [0.66349464 0.15559818 0.92419393 0.75297869 0.63576523]]
[[-0.11377997 -0.71414226  0.09827664  0.07613313 -0.00243462]
 [ 0.39368527 -0.46936446 -0.39888112 -0.60216333  0.21749294]
 [-0.56204877  0.52688486  0.0134781  -0.44304693 -0.68810997]
 [-0.38778876  0.09839136  0.50020829 -0.19337532  0.40950662]
 [-0.56703238 -0.00762356 -0.73241973 -0.56299979 -0.12230134]]


In [8]:
import numpy as np
import datetime

start=datetime.datetime.now()
print(start)

i=0
#process = True

while True:
    l=[]
    x=np.random.rand(5,5)
    y=np.random.rand(5,5)
    z=np.diag(x-y)
    i+=1
    
    for j in z:
        if -0.1 < j < 0.1:
            l.append(j)
            #if len(l) == 5:
                #print(x-y)
                #break
    
    if len(l) == 5:
        print(x-y)
        break
    
print('counter: ' , i)
    
end=datetime.datetime.now()
process_time=end-start
print('process_time: ', process_time)

2022-06-10 05:58:56.924282
[[ 0.03960991  0.42123998 -0.24723164 -0.15934295 -0.33332144]
 [-0.44716988  0.03313372 -0.20934631 -0.02455545 -0.11275472]
 [ 0.61593386  0.05307037  0.00888838 -0.33314471  0.28926202]
 [ 0.54477093  0.07777432  0.38679722 -0.01033864 -0.34771087]
 [ 0.69871231 -0.18446275  0.41773799  0.08478871 -0.08801052]]
counter:  3299
process_time:  0:00:00.041196
